#!/bin/sh

xrdb -quiet -merge -nocpp "$HOME/.Xresources"
xsetroot -cursor_name left_ptr
sh ~/.fehbg
/usr/lib/org_kde_powerdevil &
#xautolock -time 10 -locker "/usr/lib/kscreenlocker_greet --immediateLock" -noclose &
stalonetray &
dunst &
#kded5 &
