#!/bin/sh

xrdb -quiet -merge -nocpp "$HOME/.Xdefaults"
xsetroot -cursor_name left_ptr
xprop -root -f KDE_FULL_SESSION 8t -set KDE_FULL_SESSION true
xprop -root -f KDE_SESSION_VERSION 32c -set KDE_SESSION_VERSION 5
/usr/lib/org_kde_powerdevil &
start-pulseaudio-x11 &
dockd --daemon &
